compile:
  stage: build
  only:
    - main
  script:
    - docker system prune -f
    - docker-compose build
test:
  only:
    - main
  stage: test
  script:
    - ./test.sh
deploy:
  only:
    - main
  stage: deploy
  script:
    - ./start-stag.sh
