compile:
  stage: build
  only:
    - main
  script:
    - sudo docker system prune -f --all
    - sudo docker-compose build
test:
  only:
    - main
  stage: test
  script:
    - sudo ./test.sh
deploy:
  only:
    - main
  stage: deploy
  script:
    - sudo ./start-stag.sh
