stages:
  - deploy-public

default:
  image: ubuntu:20.04

deploy-heroku:
  stage: deploy-public
  inherit:
    default: false
  image: dpl:latest
  script:
    - dpl --provider=heroku --app=gpqueue-year-2-web-app --api-key=$HEROKU_TOKEN

