stages:
  - deploy-public

default:
  image: ubuntu:20.04

deploy-heroku:
  stage: deploy-public
  inherit:
    default: false
  image: travisci/ci-ubuntu-2004
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=gpqueue-year-2-web-app --api-key=$HEROKU_TOKEN

