version: "3"
services:
  backend:
    build: ./backend
    environment:
      - PORT=5000
    ports:
      - 5000:5000
  frontend:
    build: ./frontend
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
