version: "3"

services:
  backend:
    container_name: backend
    build: ./backend

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/node_modules:/app/node_modules

  nginx:
    container_name: web
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80/tcp
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
