version: "3"

services:
  db:
    container_name: db
    image: redis:6.2.4-alpine
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
    command: "redis-server --port 6379 --appendonly yes"
  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - db
    environment:
      - PORT=5000
      - gpu=${gpu:-false}
    volumes:
      - ./backend/src:/backend/src

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
  nginx:
    container_name: web
    image: nginx
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80/tcp
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

